version: "3.7"
services:
  db:
    image: mysql:8.0
    container_name: case-management-db
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: case_management_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: case_management_db_usr
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - teamgeek
  nginx:
    image: nginx:1.17-alpine
    container_name: case-management-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - teamgeek
  test-app:
      build:
        args:
          user: teamgeek-user
          uid: 1000
        context: ./
        dockerfile: Dockerfile
      image: case-management-test
      container_name: case-management-test-container
      restart: unless-stopped
      working_dir: /var/www/
      volumes:
        - ./:/var/www
      networks:
        - teamgeek

networks:
  teamgeek:
    driver: bridge